#!/bin/bash

#scripts/console cache:clear --no-warmup
#docker-compose exec php vendor/bin/codecept run acceptance

#scripts/resetapp
rm -rf var/cache/*
docker-compose exec php vendor/bin/codecept run acceptance $@ -c src/AppBundle
